"""GitHub Actions workflow template generation.

Generates YAML workflow files that integrate CodexA analysis into
CI pipelines.  Templates are plain strings — no YAML library required.
"""

from __future__ import annotations

from typing import Any


def generate_analysis_workflow(
    *,
    python_version: str = "3.12",
    trigger: str = "pull_request",
) -> str:
    """Generate a GitHub Actions workflow for CodexA analysis on PRs.

    The workflow:
    1. Installs CodexA and dependencies.
    2. Runs ``codex quality`` on the repository.
    3. Runs ``codex pr-summary`` on changed files.
    4. Posts a summary comment (advisory only).
    """
    return f"""\
# CodexA Analysis Workflow
# Auto-generated by `codex ci-gen`
# This workflow runs CodexA quality and PR analysis on pull requests.
# All outputs are advisory — CodexA never modifies repository code.

name: CodexA Analysis

on:
  {trigger}:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: CodexA — Initialize
        run: codex init

      - name: CodexA — Quality Report
        run: codex quality --json > quality-report.json
        continue-on-error: true

      - name: CodexA — PR Summary
        run: codex pr-summary --json > pr-report.json
        continue-on-error: true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: codex-reports
          path: |
            quality-report.json
            pr-report.json
"""


def generate_precommit_config() -> str:
    """Generate a ``.pre-commit-config.yaml`` snippet for CodexA hooks.

    Uses the ``local`` repo type so no external hook package is needed.
    """
    return """\
# CodexA pre-commit hooks
# Add this to your .pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: codex-safety
        name: CodexA Safety Check
        entry: codex quality --safety-only --pipe
        language: system
        types: [python]
        pass_filenames: false

      - id: codex-quality
        name: CodexA Quality Check
        entry: codex quality --pipe
        language: system
        types: [python]
        pass_filenames: false
"""


def generate_safety_workflow(
    *,
    python_version: str = "3.12",
) -> str:
    """Generate a lightweight safety-only workflow for fast PR checks."""
    return f"""\
# CodexA Safety Check
# Lightweight workflow — validates changed code for security patterns.

name: CodexA Safety

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: CodexA — Safety Validation
        run: codex quality --safety-only --pipe
"""


TEMPLATES: dict[str, str] = {
    "analysis": "Full analysis workflow (quality + PR summary)",
    "safety": "Lightweight safety-only workflow",
    "precommit": "Pre-commit hook configuration",
}


def get_template(name: str, **kwargs: Any) -> str:
    """Get a named template. Raises ``KeyError`` for unknown names."""
    generators = {
        "analysis": generate_analysis_workflow,
        "safety": generate_safety_workflow,
        "precommit": generate_precommit_config,
    }
    gen = generators.get(name)
    if gen is None:
        raise KeyError(f"Unknown template: {name!r}. Available: {', '.join(generators)}")
    return gen(**kwargs)
